### ISSUE TITLE
Animation error, while the error is occurring

### ISSUE THREAD

**Issue by DrSa1fer** [theakopov/fcloud#1]
I accidentally tried to upload a non-existent file via fcloud add. And when the error occurred, the animation characters didn't disappear. It doesn't affect performance in any way, but I think it might be distracting (since it might not only happen with fcloud add).
![Screenshot from 2024-07-06 17-36-21](https://github.com/theakopov/fcloud/assets/112440539/a2ffc878-d358-4cc6-aaaf-a9c8a1a61786)

**Comment by theakopov** [comment]
Hi! Yes, indeed, this error started appearing after commit 687b1a6 (for 3 July). We have made changes to the error output system, and now everything should work correctly when updating fcloud packages.
_Here is fix:_
https://github.com/theakopov/fcloud/commit/e613978f736780d2a1e1723c4ba3429f4213391a
